import{a as w,S as B,i as n}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const q="https://pixabay.com/api/",A="51926469-17331259ac3d6722fcf98d7c3";async function p(s,o){const t=await w.get(q,{params:{key:A,q:s,image_type:"photo",orientation:"horizontal",page:o,per_page:15,safesearch:!0}});return console.log(t.data),t.data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".load-more"),$=new B(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){const o=s.map(({webformatURL:t,largeImageURL:c,tags:e,likes:r,views:i,comments:v,downloads:S})=>`
    <li class="gallery-item">
      <a href="${c}">
        <img src="${t}" alt="${e}" loading="lazy">
      </a>
      <div class="info">
        <p><b>Likes:</b><br>${r}</p>
        <p><b>Views:</b><br>${i}</p>
        <p><b>Comments:</b><br>${v}</p>
        <p><b>Downloads:</b><br>${S}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",o),$.refresh()}function C(){f.innerHTML=""}function b(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}function m(){g.classList.remove("hidden")}function F(){g.classList.add("hidden")}const l=document.querySelector(".form"),E=l.querySelector('input[name="search-text"]'),M=document.querySelector(".load-more");let a=1,d="",u=0;l.addEventListener("submit",async s=>{s.preventDefault();const o=E.value.trim();if(o){d=o,a=1,C(),F(),b();try{const t=await p(d,a);if(!t.hits||t.hits.length===0){n.error({message:`Sorry, there are no images matching your search ${o}. Please try again!`,position:"topRight",timeout:5e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB"});return}u=Math.ceil(t.totalHits/15),y(t.hits),a>=u?(m(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topright",timeout:5e3})):m()}catch(t){n.error({message:t.message,position:"topRight",timeout:5e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",class:"error-toast"})}finally{L(),l.reset()}}});M.addEventListener("click",async()=>{b();try{a+=1;const s=await p(d,a);y(s.hits);const o=document.querySelector(".gallery.item");if(o){const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}a>=u&&(F(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topright",timeout:5e3}))}catch(s){n.error({message:s.message,position:"topRight",timeout:5e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",class:"error-toast"})}finally{L()}});
//# sourceMappingURL=index.js.map
